### ISSUE TITLE
Dead loop on start session error 

### ISSUE THREAD

**Issue by lance6716** [getlantern/lampshade#42]
https://github.com/getlantern/lampshade/blob/2e7977c8e74cd5959f3f506f1128daca3af0ade4/dialer.go#L155-L162

here `err` from `startSession` won't be passed to caller function, which will cause `getOrCreateSession` never return.

How about retry and return error?

**Comment by joesis** [comment]
`getOrCreateSession` has a for loop which eventually return once `<-ctx.Done()`.
